### ISSUE TITLE
Can not login into home assistant remotely

### ISSUE THREAD

**Issue by slonkar** [home-assistant/home-assistant-iOS#170]
I am running the latest build of HomeAssitant iOS App from Testflight (1.5.0 Beta) and I am having an issue logging in remotely. On App launch, I enter my duckdns url and click validate and save connection setting option, which pushes the login page. After entering credentials I just get please wait message and that’s it.

Just noticed that URL shown on the screenshot is not my homeassitant URL. Is anyone doing fishing?

I have tried accessing homeassitant remotely via web and it works as expected so I don’t think there is an issue with duckdns or port forwarding. Also, I am able to log in using the app if I am on the same network.

Any comment/feedback is highly appreciated

![login](https://user-images.githubusercontent.com/1111633/48869858-81e45380-ed93-11e8-90aa-e52dde9cd665.png)

![afterlogin](https://user-images.githubusercontent.com/1111633/48869845-77c25500-ed93-11e8-85a1-8fcd06c44177.png)

Setting Screen Shot

![image1](https://user-images.githubusercontent.com/1111633/48919395-75213780-ee47-11e8-9391-7b6037d19201.png)

If i try to use legacy authentication then I get following error.
![img_1159](https://user-images.githubusercontent.com/1111633/48919520-17d9b600-ee48-11e8-97ee-29186a208629.PNG)

**Comment by robbiet480** [comment]
@slonkar Is this still an issue?

**Comment by christianwaite** [comment]
I have exactly the same issue. Nginx reverse proxy with duckdns and let’s encrypt. I just moved over to a new setup with nginx-proxy-manager and get the same results.

iOS app on Wi-fi works
iOS app on cellular doesn’t 
iOS safari on cellular does
iOS app on external Wi-fi network works.

It’s only the iOS app that has a problem.

**Comment by slonkar** [comment]
@robbiet480 No I ended up nuking the whole set up and doing it all over again. No issues with remote login anymore. @christianwaite Are you still seeing this issue? If not I can close it.

**Comment by OttPeterR** [comment]
I believe I'm having this issue, exactly as described by @christianwaite : nginx rev proxy, duckdns, and letsencrypt, router port 80 and 443 forwarded from router to HA nginx proxy, 8123 also to HA instance

what I have noticed:
- app works locally via IP:port
- ios app does not load UI externally through reverse proxied name
- browser on ios will load HA externally through the reverse proxied name
- I _think_ that my wifes android app works remotely, so its an ios app specific thing, again I _think_
- ios app will send data like location, battery, actions, etc through the external connection, so some external connections are working
- home assistant shows a notification "Login attempt failed", "Login attempt or request with invalid authentication from <IP>" upon the first attempt to connect externally with the app
- ios app will work for like 5 minutes after disconnecting from local network and going to external network, so following that error message from above, it could be authentication issue that's being caused by the proxy in the middle
- HA logs and app logs dont seem to show much more than that unfortunately (or I'm not looking in the right place)

**Comment by stefancvetkovic** [comment]
me too, Im not be able to login remotely. Im using also nginx on default port 443..
