### ISSUE TITLE
Force location update responds with 404

### ISSUE THREAD

**Issue by cmsimike** [home-assistant/home-assistant-iOS#195]
Thanks for getting 1.5 out the door!
I've logged in using my own user and have been poking around in the UI and one thing I noticed is that if I use the force update button on the map screen, I get a 404 response:

"failed to send current location to the server. the error was response status code was unacceptable: 404"

**Comment by towerhand** [comment]
What have you tried so far?

**Comment by cmsimike** [comment]
@towerhand I hit the button and got a 404. Do you have any other suggestions on what to try?

**Comment by towerhand** [comment]
You could try to log out and logging back in, resetting the app, removing and reinstalling, removing the iOS: component from HA and setting back up.

Those are just recommendations (I’m not a dev or mod) and usually things I do before submitting an issue. If that doesn’t fix it then please provide more info like HA version, installation method (hassio?), iPhone and iOS versions, the more information the better.

**Comment by ronytomen** [comment]
Using native authentication in the updated IOS app I do not get a "404" but do get a failed authentication attempt.

```
2019-01-16 13:58:25 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.xxx.xxx
```

**Comment by arsaboo** [comment]
Disable `ip_ban` and try.  Also, what do you mean when you say `native authentication`? The new auth?

**Comment by ronytomen** [comment]
@arsaboo there is no need to disable `ip_ban`. There are no IP addresses currently banned for the subnet which the IOS device is generating traffic from. 

New auth is referred to as `native authentication`in the Home Assistant documentation. 

Sending a location update is failing due to authorization failure, status code `401`. When `legacy authentication` was enabled it would authorize but fail with a status code `404`. 

Seems to be a disparity between what Home Assistant IOS Componet expects and what the newly updated IOS app is doing. 

Running HA Version 0.84.6.

**Comment by mnoorenberghe** [comment]
@cmsimike Are you using legacy auth or the new auth? I'm trying to understand if ronytomen is having the same issue as you or not.

**Comment by robbiet480** [comment]
@cmsimike Still having issues?

**Comment by robbiet480** [comment]
@cmsimike reports this has been resolved after a reinstall, although a 404 is a server side error. Closing anyway!
