### ISSUE TITLE
iBeacon updates not triggering 1.5

### ISSUE THREAD

**Issue by abarbaccia** [home-assistant/home-assistant-iOS#199]
iBeacon was working correctly in beta 32. In beta 3r this stopped working correctly and is also not functioning in 1.5 release. 

There seems to be a location update triggered, but then decides not to send to ha since the database already shows the correct value. 

More details here
https://community.home-assistant.io/t/ibeacon-on-1-5-0-not-updating-zone/92236

**Comment by jwelter1971** [comment]
I'm see the same thing.  To test this morning my wife and I left the house together; her iPhone on 1.5 beta 32 mine on the official release of 1.5.  Her device registered the ibeacon zone exit; mine did not.  Her phone was immediately marked as away from home; mine took ~10 minutes until a significant update was triggered.

On returning home as soon as garage door opened her phone did a zone enter on beacon while my phone still hasn't picked up it's home with the iOS app.  

So something is certainly messed up.

**Comment by burzka** [comment]
I have very the same issue. I think that ignoring iBeacon exit event can be usefull when iBeacon signal is weak or unstable. It will avoid unwanted zone switching. But do anyone knows if that works that way? What's the purpose of that? In my opinion it should work that way:

1. [entering iBeacon home zone] -> Sending enter zone message to HA (with fixed gps coordinates from HA config).
2. [staying in iBeacon range] -> Turn off all GPS data catching/sending to HA. Don't fetch GPS in background etc. If iBeacon connection dropped, wait for 5 minutes (or other, choosen by user). During this delay time, don't send any GPS data to HA (I think it isn't work that way on any build), and wait for iBeacon reconnect.
3. [iBeacon connection still dropped OR going outside iBeacon home zone] -> After that 5 minutes without iBeacon connection, trigger iBeacon exit event and start fetching GPS data, send it to HA.

As You said, build 34 doesn't pass any iBeacon enter zone data to HA. But build 32 isn't perfect too. For some reason even if I'm in iBeacon zone, iOS app can send some GPS data (background fetch) to HA. After that there is no possibility to trigger "iBeacon enter zone" because in fact, I'm still in that zone and nothing has changed. I must go outside iBeacon range for a few minutes (to drop iBeacon) and after this time, when I enter that zone, the event will be triggered. When I'm in iBeacon range, iOS app should always send that data to HA instead of GPS info (in my opinion even on manual posiotion change).

In addition it will be very usefull to set in the app kind of iBeacon connection indicator.

**Comment by jwelter1971** [comment]
Perhaps we need a "consider_away" setting like some of the other trackers so we can tune how long after a beacon exit do we assume away.  

Right now the app is not suitable for me as a beacon exit was the best method of detecting us away.  This is because our exit street sort of loops around and takes us back to within a few hundred meters of our house about 3 minutes after leaving.  So often this confuses the significant location update; as a result it takes 15 minutes or so to detect we're away.  

With beacon exits working this would be a couple seconds.  basically as soon as garage door closed beacon would not be visible.

**Comment by jjlawren** [comment]
This seems to be a result of my PR here: https://github.com/home-assistant/home-assistant-iOS/pull/180.

The idea (discussed in Discord) was that iBeacon exit events can be very flaky with many false positives, so falling back to GPS as a "true" zone exit trigger was more reliable. However, the PR above broke iBeacon handling completely as it appears to be stuck in the first iBeacon region you enter indefinitely.

**Comment by burzka** [comment]
@jwelter1971 My "home" zone is "passive" type to avoid GPS entering. Even if exit event isn't triggered to HA, after any iBeacon signal loss, iPhone sending GPS location (for example Background Fetch) and kicking me out of home zone. Changing to "active" zone is kind of solution, but I want trigger enter event only after iBeacon signal.

**Comment by jwelter1971** [comment]
@jjlawren Yes, iBeacon exits can be flakey unless you ensure you have proper coverage over the entire zone.  For this reason I have 5 ibeacons needed to cover my home zone and since doing that iBeacon exits from my home zone have been 100% reliable.

As I mentioned above perhaps we need to tackle this like the device_trackers have done so with a configuration option like “consider_exit”.  This would simply be a delay when iBeacon signal lost before signaling an exit.  If the signal returned during the delay it would not signal an exit.  

For your use case you could set it artificially high which would accomplish disabling iBeacon exits but for those of us with good coverage we could set it to a much lower value.

Also to disable iBeacon exists why can’t the toggle be used in the app configuration versus disabling it for everyone?  It seems unexpected that if its enabled in the configuration options to use iBeacon enter/exits that they are used?

As it is now the iOS app is not usable for presence detection because of this.  

> This seems to be a result of my PR here: #180 (or maybe #176).
> 
> The original problem was that if you had multiple zones that contained iBeacons, exiting a non-home iBeacon region would trigger your location to immediately enter the `home` zone, which was incorrect.
> 
> Additionally, iBeacon exit events can be very flaky with many false positives, so falling back to GPS as a "true" zone exit trigger was more reliable.
> 
> Solving both of these issues was the intention. Unfortunately, the PR above broke iBeacon handling completely as it appears to be stuck in the first iBeacon region you enter indefinitely.

**Comment by jjlawren** [comment]
Yep, agreed and the current behavior wasn’t intended. I’m hoping to submit a PR soon to fix (or revert) this after it’s better tested.

Longer-term it makes sense to reimplement some of the logic used by other proven trackers like OwnTracks which use optional exit timeouts like you describe.

**Comment by abarbaccia** [comment]
Thanks everyone 

One additional suggestion... and I’m not super close to the logic so not sure if it would work for others.. 

But If iBeacon exit is triggered, should we not fall back / push gps location update? Right now when you exit iBeacon it seems we assume away. Then if your phone triggers gps update you get marked back home. But my house has bad gps coverage so there are infrequent updates. So when I leave iBeacon zone I get marked away. But if I push the manual gps update button on the app it marks me back home.  

_____________________________________________________________________________________________________

Andrew Barbaccia 
Principal
THE BOSTON CONSULTING GROUP
Mobile +1 2015638617

_____________________________________________________________________________________________________

**Comment by robbiet480** [comment]
@jjlawren Where you at on this? Should we just revert one or both of the PRs?

**Comment by jwelter1971** [comment]
@robbiet480 Hi Robbie - I'd like to test this to see if it clears the problem.  But my TestFlight seems stuck at 1.5 b34 being listed as the latest.  Do I need to do something to get the current Testflight releases that are post-1.5 public release?

**Comment by jjlawren** [comment]
@jwelter1971 the most recent TF releases weren't sent to everyone. My own tests on #209 look promising, so hopefully it can go to everyone soon for further testing.

**Comment by robbiet480** [comment]
This is in the pipe for 1.5.1 which is held up on a metadata rejection. I'll be handling that issue tomorrow and expect Apple to approve very shortly thereafter, so closing this issue for now.
