### ISSUE TITLE
Siri shortcut "alarm_control_panel.alarm_arm_away with data" truncates leading 0 from code

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-iOS#222]
On build 2.0.0 (22) setting a siri shortcut to arm the alarm control panel removes a leading zero from the pin code (e.g. "0123" turns into "123").

**Comment by robbiet480** [comment]
@olbjan Okay, after investigating this further, I'm going to decline to make changes to the iOS app. This is a problem with [the `services.yaml` for `alarm_control_panel`](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/alarm_control_panel/services.yaml). It should be defining the `code` field on every service as a string, not a integer (so, just adding quotes around the examples) since everything relating to programming would treat a integer `0123` as actually `123`, but a string would be left alone.

I'd suggest opening a issue on the primary repo, or even better submitting a pull request to fix services.yaml.

**Comment by robbiet480** [comment]
[Hah, in fact you can blame me for making the code a integer](https://github.com/home-assistant/home-assistant/commit/a93195610a5d370d4832704b8cdc2e784cdbf487) as I was the original creator of the schema.
