### ISSUE TITLE
Special chars borked in watch complications preview

### ISSUE THREAD

**Issue by krissen** [home-assistant/home-assistant-iOS#253]
Special characters, such as åäö for instance, do not show correctly in watch complication preview.

Regardless if in templates or entered as plain text (as in the image attached), it looks like the following:
![06EC4F1F-62CF-4DF7-9E32-714A2C0B9E5B](https://user-images.githubusercontent.com/2943684/55580669-5c8d2c00-571b-11e9-8643-3d375ee9520e.jpeg)

As expected, similar result with emojis:
![B66FFDA4-B722-418D-838F-9E1594B78BF2](https://user-images.githubusercontent.com/2943684/55580785-9b22e680-571b-11e9-8f19-7ac2da3d31e7.jpeg)

**Comment by krissen** [comment]
They _do_ work on the Watch though! 
![FFDCEDEB-4190-4B5B-8BA5-84D29ACF9E5B](https://user-images.githubusercontent.com/2943684/55581057-3f0c9200-571c-11e9-8b3c-205b6aecdafc.jpeg)

**Comment by SeanPM5** [comment]
A development decision was made to delay Watch and Shortcuts support from the 2.0 app and re-implement them in version 2.1 as iOS 13 specific features. 

Not only will this allow 2.0 to be released very soon, but the nice improvements coming with iOS 13 will make the Watch and Shortcuts integration better and easier to use - it'll be worth the wait!

I've been asked to close all existing Watch and Shortcuts-related issues since things will be changing a bit. Stay tuned in the coming weeks.
