### ISSUE TITLE
mobile_app Integration not cleaning up Nabu Casa cloud Webhooks

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-iOS#261]
The mobile_app integration creates Nabu Casa Webhooks upon setup of the iOS companion app. These are not removed when the integration is removed from HA.

This is a) not necessary when remote control is disabled and b) cannot be removed by the user. As the Webhooks always get created with the same name you quickly end with a list of multiple dead entries.

I added this issue here because it's @robbiet480 's work but I believe this might need to be moved to the Cloud repo.

-Jan

**Comment by robbiet480** [comment]
Couple of things:

1. Cloudhook != Remote UI. Cloudhook is always preferred over using the Remote UI due to the Remote UI requiring authentication
2. Webhooks are removed when the integration is. Well, they aren't removed exactly, they are marked as deleted by `mobile_app` which will start returning a `410 Gone` HTTP status so that apps know the user intentionally deleted the integration and reset themselves/alert the user.
3. There are already plans to be able to mark Cloudhooks and Webhooks as "managed" which will remove them from the users view entirely.
