### ISSUE TITLE
[2.0b43] Lokalised sensor names

### ISSUE THREAD

**Issue by mgiako** [home-assistant/home-assistant-iOS#284]
The new sensors of the 2.0 app (42 & 43) can be translated with lokalise. I believe this possibility should be removed because anyone can access lokalise and change the names of the sensors causing a breaking change for the whole nation that uses that language. I think it's much better to leave the English version for everyone. In this way also the documentation will be uniform for all.

**Comment by olbjan** [comment]
I concur, better to keep the default sensor names consistent in english and thus consistent with docs. Renaming can be done later by the user.

**Comment by olbjan** [comment]
The localised sensor names must be a bit deeper than expected. I have renamed the german sensors in lokalise to match the original english string and have successfully updated the lokalise bundle in the app. When running through onboarding again though, all sensors once again get created with the german strings.
Also, because the German translation for "activity" includes an Umlaut (Aktivität), that sensor does not get created whatsoever.
