### ISSUE TITLE
Access via VPN (VPN-on-Demand)

### ISSUE THREAD

**Issue by mag2bue** [home-assistant/home-assistant-iOS#328]
Feedback / Issue of my testing! 

Hello,

I'm testing the new beta version 2.0.0 (51) / HA 0.92.2.
I would to control my home via VPN. Usually VPN on Demand.
Bit when I open the app, VPN will not start automatically. Always the App crashed.
If I start VPN manually, it is as well not possible to connect. As well, the App crashed after 1-2 seconds.

To put my internal link as external is not possible. Could not be saved.

It will be very helpful, to have a connecting via VPN (VPN on Demand) Because I didn't won't to have a connect directly to the internet.

**Comment by sgruby** [comment]
I think the app is expecting an external URL if you are connecting from an SSID not listed. Unfortunately in 52, I'm unable to get an external URL to save (I set it to the same as my internal URL). I'd think that if the external URL is empty, it would always attempt to use the internal URL even if the SSID doesn't match. This behavior changed since yesterday as I used the app with an on-demand VPN last night before upgrading this morning.

**Comment by robbiet480** [comment]
I believe you also need the profile containing the VPN settings to specify on demand activation for the bundle ID (`io.robbie.HomeAssistant.beta` and soon `io.robbie.HomeAssistant` once its released to the store).

**Comment by mag2bue** [comment]
@robbiet480 In my case, VPN-on-Demand is controlled by the Domain. If I have any request to my local network, VPN will start.

btw, if I'm not connected with my home wifi, I can't start the App (2.0.0(52)) crashed with error message. 
...VPN doesn't matter..

**Comment by mag2bue** [comment]
2.0.0 (53) external link is now working.  Access via VPN is possible.  

Solution: I added the internal link as well as an external link.
