### ISSUE TITLE
Missing device_tracker in version 2.0 beta

### ISSUE THREAD

**Issue by rgruyters** [home-assistant/home-assistant-iOS#338]
For a while now I'm missing the `device_tracker.iphone_van_robin_beta` in HA. It doesn't get updated anymore. I have tried to remove it from my `known_devices.yaml` unfortunately it doesn't help.

In my configuration I load the different components as `packages:` I don't know if this could be the issue.

Also I'm loading both the `mobile:` and `iphone:` component.

My full configuration can  be found at: https://github.com/rgruyters/home-assistant-config.

Currently i'm running Home Assistant Companion 2.0.0 (53) with HA version 0.92.2.

**Comment by SeanPM5** [comment]
Thanks for the report. This is a known issue.

The current version of the beta does not use the device ID and instead uses a 32 character random UDID for the `device_tracker` entity_id. It should look something like this in your `known_devices.yaml` file (or search your States page for `device_tracker` and then look for the random number like this). 

```
90bf462b364a40a08813874de4779b31:
  hide_if_away: false
  icon:
  mac:
  name: 90bf462b364a40a08813874de4779b31
  picture:
  track: true
```

**The good news is this is only a temporary thing**. The device name functionality will be restored in a future iOS 2.0 beta, but it requires changes to the Home Assistant core first, so it's waiting on Home Assistant version 0.93.  (Same for the missing "App Configuration" label in the sidebar.)

Hopefully that explains it well and sorry for the inconvenience. I am closing this issue since it's being worked on already, but if you have any questions feel free to ask.
