### ISSUE TITLE
2.0 Beta queries

### ISSUE THREAD

**Issue by jjpeet** [home-assistant/home-assistant-iOS#342]
Hi @robbiet480 it has taken me some time to get around to testing v2 but today I removed the old app and loaded v2.  A few questions;

1. Is there a way in the new app to push your location (it was a button at the bottom of the screen in 1.5)
2. I'm trying to ensure that this app is in known devices and is the same entry as my old app. The old app allows me to check the name from iOS (jamess_iphone). I'm not sure how to verify its doing the same thing.
3. Related to 2 no doubt but when I request a location via push, my app doesn't do anything.
4. I use internal DNS and external DNS - both https://hass.jjpeet.com. I can't seem to get the new app to understand that I'm not interested in internal/external connectivity. Just a single connection type that works anywhere with the one DNS name is all I'm after.

That's all for now - the app is looking awesome by the way and once I get past these basic issues, I'll starting testing it with actions and Siri shortcuts.
Thx
JP

**Comment by SeanPM5** [comment]
Hi, I'll try to help answer some of your questions.

1. In the 2.0 app when you pull down to refresh, it also performs a manual location update just like the button in the old app. It no longer shows the success prompt, but you can see the results in the `sensor.last_update_triggered` sensor to confirm it's working correctly. 

2. In the current beta build the `device_tracker` uses a unique 32 character UDID instead of the device name. For example mine is `90bf462b364a40a08813874de4779b31` so look for something similar to that in your known devices. This is only temporary. The ability to use your device name (jamess_iphone) like before is being restored in a future build, but it's been held up a bit since it requires changes in Home Assistant 0.93 first.

3. The reason that your push location updates aren't working is that `notify.ios` prefix has been changed to `notify.mobile_app`. You can find the exact name from the dropdown list on the Services page in Home Assistant and more info on notifications [here](https://companion.home-assistant.io/en/next/notifications/basic).

Robbie is better suited to answer question 4. But I do know all the connection stuff is something that's being actively worked on and was the main focus of the past week.

**Comment by jjpeet** [comment]
Hi @SeanPM5 
Thanks for that - after a few attempts to load the beta over the last few weeks, I discovered a bunch of unavailable entities in the entity registry - I'm starting to get how it's all working now.
I removed all of those and the 5 or 6 mobile_app integration entries and started again and reloaded the app.
Now I get two device_trackers - the UID from the new mobile app, and also the MAC address one from nmap which I've mapped to person.james

Push is still an issue - there isn't any notify.mobile app in there at the moment, but I'll continue tinkering until I figure out what's happening.

Also, I'll wait for the future builds to see what's happening with connections.

thx
James

**Comment by SeanPM5** [comment]
For the `notify.mobile_app` service to show up, sometimes you must restart Home Assistant more than once. Going into the apps "Notifications" settings and then pressing the "Import push configuration from server" might help as well.

**Comment by jjpeet** [comment]
Hi @SeanPM5 that did the trick - thanks,
JP

**Comment by jjpeet** [comment]
Hi @robbiet480 Regarding point 4 above; I've been using Nabu Casa remote configuration so that the Beta 2.0 on my phone works when I'm away from home. Having used it for a few weeks now, its performance is pretty crappy no doubt because I'm in Australia. The old app just updates instantly whether I'm at home or away because I'm using a DNS entry that goes direct to my place (rather than through North America).

So if you're able to allow a single DNS entry for all connectivity, or a manual config for internal & external DNS entries that would be appreciated.
Thx
JP

**Comment by TomBrien** [comment]
I believe all this is covered by the release and so I’m closing feel free to reopen if I’m wrong
