### ISSUE TITLE
No Timestamp against location update?

### ISSUE THREAD

**Issue by Swiftnesses** [home-assistant/home-assistant-iOS#343]
Good day,

Using the previous 'ios' implementation I used the timestamp against the location update to trigger various automations, I can't seem to locate this attribute anymore, can it be re-added?

**Comment by SeanPM5** [comment]
Hi there.

In 2.0 there is a new `sensor.last_update_trigger` which is a lot more powerful than before. It not only tells _when_ your location was updated, but what location update method update was used too (for example Background Fetch, Siri, zone exit/entrance, push notification, etc). I wrote the docs for it [here](https://companion.home-assistant.io/en/next/integrations/sensors#last-update-trigger-sensor).

This is how you would get the timestamp for use in automations:

`{{ states.sensor.last_update_trigger.last_changed }}`

It will return the following: 2019-05-07 15:11:32.249633+00:00

And to get the state (for example "Background Fetch") use this: 
`{{ states.sensor.last_update_trigger.state }}`

Just be aware that because some beta builds that forced the onboarding/setup screen you might have multiple Mobile App integrations (under Configuration -> Integration) so your sensor might be called something like `sensor.last_update_trigger_2` or `_3` for example. If this is the case for you, to find the correct one just pull-to-refresh which initiates a location update and then find the sensor that actually updated. (You can also find detailed instructions [here](https://companion.home-assistant.io/en/next/misc/beta-cleaning) on how to clean up the beta duplicates). 

Let me know if this helps.

**Comment by Swiftnesses** [comment]
@SeanPM5 Got the timestamp back working, thanks...

I need to figure out what's up with my sensors since the upgrade though. I sanitised everything before updating the beta and the sensors got created fine (I am however missing floors ascending and floors descending from my XR). The main issue is that sensors do not seem to be updating after the initial install readings...

**Comment by gcobb321** [comment]
**@SeanPM5** 

A bigger problem with the sensors right now is tying them to a specific device. My wife and I both have iphones that are tied to different device tracker entities and used in different automations and scripts. Telling which sensor belongs to me and which sensor belongs to my wife is impossible. I know Robbie said the device name will be added back to the ios app which should solve that issue, but until then, we are kinda stuck. 

When I added sensors for most of the tracker attributes in v1.0.3 of [iCloud3](https://github.com/gbobb321/icloud3). I used the 'sensor.gary_iphone_attributename' format for example and that made them easily to recognize as individual devices in automations and scripts. 

iCloud3 monitors the tracker state changes and trigger notifications issued from the device for presence detection and to know when a device enters and exits a zone. This cannot be done without knowing which device is tied to which tracker or sensor and knowing which ones I need to monitor. Any help or information on what I need to do to make iCloud3 compatible with the new ios app would be greatly appreciated. I would really like to get everything working together before the final release. 

My email address is geekstergary@gmail.com.

**Comment by SeanPM5** [comment]
@Swiftnesses There was an issue with motion permissions not being set correctly in an earlier beta build. You can try going to the  iOS Settings app, scroll down to Home Assistant B and make sure that the "Motion & Fitness" toggle is on (green). If that's toggled on and the sensors are still not updating, you might have to try reinstalling the Home Assistant beta app again.

@gcobb321 I agree that the current naming setup with the sensors is inconvenient, especially when dealing with multiple devices. It's only a temporary beta thing though - the device name functionality _will_ be restored and then you'll be able to have nicer, easy to identify user-specific entity id's (`sensor.gary_iphone_battery_level`) just like before. 

Because the new 2.0 mobile app is much more tightly integrated into Home Assistant, certain changes like this device name one also require changes to Home Assistant core as well, so that's why it's taking a bit longer than a lot of the other fixes. My understanding is that this should get sorted out before the final release.

**Comment by gcobb321** [comment]
**@SeanPM5** Thanks for the info and I look forward to the upcoming release where i can tie iCloud3 back together with the ios app for zone changes and location taking. 

A couple of questions and thoughts...
1. I see the location tracking (latitude and longitude) are part of the geocoded_location sensor and the trigger sensor describes the last trigger.  I am checking the device_tracker.devicename sensor for location, state and trigger changes that are updated by  `see`. Will this info also be available as attributes on the device_tracker.devicename sensor like it is now? Or will I have to monitor the individual sensors to get the data I need? 
2. Any thoughts on how best to resolve the `sensor.XXX_distance` name conflict where you are using it for walking and I am using it for the distance from home? Obviously, I can change the name to something like `distance_from_home` and you can change it to `walking_distance` or both of us change the name. The goal should be to eliminate user confusion since the icloud3 and your new sensors will all be listed together in HA entities states list.  
3. Could include the zone name being exited from or entered as part of the geocoded_location sensor or the trigger sensor?

Gary Cobb

**Comment by TomBrien** [comment]
The original issue was addressed and I believe the rest is stale. Please see [release docs](https://companion.home-assistant.io/getting_started/migration) for some of the discussed points
