### ISSUE TITLE
Send to watch missing in build 55

### ISSUE THREAD

**Issue by KentEkl** [home-assistant/home-assistant-iOS#352]
![7A9145E4-FF4F-4B60-B1C5-7408C96A4BB1](https://user-images.githubusercontent.com/39707712/57396685-2f74e300-71cb-11e9-861e-48c99f281ee7.jpeg)

**Comment by SeanPM5** [comment]
Thanks for the report.  Send to watch button was intentionally removed to simplify things for users and ensure they remain within the rate limits Apple sets. 

The app handles the sending to watch part automatically now. It can take up to 30 min to sync. If it's not being sent to your watch after at least 30 min feel free to open another issue for that. Thanks.

**Comment by KentEkl** [comment]
I think this is very strange, we have been asked to put things that does not work in github so that
other users , testers will be notified about things that does not work instead of putting duplicate questions in different forums. This is a undocumented change that makes a big difference in testing the beta since we have to wait more than 30 min. until  we if see if a change we do in our tests works. And this case is closed immediate, 1 hour after the case is opened so from that no one can see that this information / change on github. I dont know if I missed something so please help me understand this.

**Comment by SeanPM5** [comment]
This is an issue tracker to report bugs & suggestions to developers, and the missing "Send to Watch" button was not a bug, it's an intentional change the developer made and is already aware of.

Things can change on a daily basis in these beta builds, and if every change was kept open here for better visibility / explanation purposes, it would be a lot harder for the developer to sift through it all and find important issues that need fixing. So no hard feelings, only trying to organize and make things easier for Robbie in the final stretch of development. 

I understand this change wasn't communicated well, but that's part of being a beta tester: lots of rapid changes with documentation updates to follow afterwards. Despite closing the issue I did my best to explain the reasoning behind it which I thought would be satisfactory.

As mentioned in my initial comment, feel free to open another issue if you're having trouble with the sync process or have a suggestion on how to better handle this.

**Comment by robbiet480** [comment]
@SeanPM5 is right. That was a temporary button while I worked on improving watch<->phone communications. It's all automatic now. No need for it anymore.
