### ISSUE TITLE
Explicit device ID removed from app settings

### ISSUE THREAD

**Issue by jschlyter** [home-assistant/home-assistant-iOS#360]
It is no longer possible to set the manually set the device ID in the app settings. Is this intentional or was the parameter lost?

**Comment by SeanPM5** [comment]
Thanks for the report, this is a known limitation right now (see https://github.com/home-assistant/home-assistant-iOS/issues/262) and the good news is that Robbie plans to fix it very soon. The functionality should be restored in one of the next few builds hopefully, so stay tuned to TestFlight. 

Closing this now since the question was answered, but once the feature becomes available for testing, be sure to report any problems you might experience with it here. Thanks.

**Comment by jschlyter** [comment]
We're closing in on release and this is still not resolved it seems? cc @robbiet480 
I have one of those devices with UTF-8 characters in my device name, so the pre-defined device id is really messed up.
