### ISSUE TITLE
Images hidden under keyboard when searching complications

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/home-assistant-iOS#363]
When selecting a image for a watch complication, if you use the search box some images will be hidden beneath the keyboard, you can tell they are there by pulling the screen a little over the keyboard. See video here: https://imgur.com/a/eIZ3avk

**Comment by SeanPM5** [comment]
A development decision was made to delay Watch and Shortcuts support from the 2.0 app and re-implement them in version 2.1 as iOS 13 specific features. 

Not only will this allow 2.0 to be released very soon, but the nice improvements coming with iOS 13 will make the Watch and Shortcuts integration better and easier to use - it'll be worth the wait!

I've been asked to close all existing Watch and Shortcuts-related issues since things will be changing a bit. Stay tuned in the coming weeks.
