### ISSUE TITLE
“Error sending Region Entered location update”

### ISSUE THREAD

**Issue by devanl** [home-assistant/home-assistant-iOS#378]
![7C4A35F1-4F28-491A-9439-1716AD430DEF](https://user-images.githubusercontent.com/4000925/57973529-27116a80-7978-11e9-8eb9-0dd86218e9de.jpeg)

Using nubu-casa cloudhooks

Zone has lat/Lon and iBeacon

**Comment by robbiet480** [comment]
Almost certainly due to your transitioning from cellular to wifi or vice versa. Is this possibly the case?

**Comment by aegjoyce** [comment]
I get a similar issue (iPhone X, latest beta version) except I have “error sending significant location update” as “the request timed out”

Interestingly I actually have all app-side location settings switched off so I would have thought it shouldn’t be trying to send any location information home?

**Comment by aegjoyce** [comment]
To add: Robbie, the amount of work you’ve done on this app in the last few months is astonishing - it looks and feels so damn slick now, the sheer number of fixes you’ve pushed is incredible, so thank you from myself and the community :)

**Comment by aegjoyce** [comment]
![38961F38-B424-4063-B407-AF930D4C0DE9](https://user-images.githubusercontent.com/47081267/57981129-78c6fd00-7a2b-11e9-90e4-508c7a6556fd.png)
![A14B6681-19D3-43AE-8066-ECFD199E923A](https://user-images.githubusercontent.com/47081267/57981130-78c6fd00-7a2b-11e9-9542-adadbabca5b7.png)

**Comment by Cludch** [comment]
I noticed this issue as well. Came up with the latest update.
It seems to come up every time I enter or leave a zone I set up. Seems unrelated to Wi-Fi or cellular switching (atleast what I observed).

iPhone X, iOS 12.3

**Comment by astrandb** [comment]
I got similar error for no obvious reason. 
iPhone X, iOS 12.3, HAC 2.0.0(58)
![IMG_0880](https://user-images.githubusercontent.com/5016010/57983758-c193ab80-7a55-11e9-92b4-a288fdb53834.jpg)

**Comment by TomBrien** [comment]
Just to weigh in that I have seen a fair few of these timeouts recently. Mainly during a recent trip to China with poor WiFi or on London Underground. Does falling off WiFi trigger a location update? All in all I felt the behaviour was expected. I believe this has been going on in the background anyway and reporting via the notification was new in 58?

**Comment by robbiet480** [comment]
SLU can be triggered by networking changes yes.

**Comment by michaeldvinci** [comment]
I also have been getting this error / notification on the most recent Companion App Beta for the last two versions, I have two zones - 'Home and 'Work' and i get this error every time I leave the lat/long radius

**Comment by krissen** [comment]
Just chiming in, that these are, indeed, very common. For zone entering / exiting, almost more often than not, when entering or exiting some of the zones I have set up. For SLU, well, often. Seemingly never when on WiFi though. (Regardless of zone.)

**Comment by devanl** [comment]
Started getting this two days ago, not sure if it’s related. 
The mobile app component appears to be installed in the integrations pane. 

![A6A9E416-C7EC-4A96-8E3B-69F8683DAE0E](https://user-images.githubusercontent.com/4000925/58750643-20e4b900-8463-11e9-909e-65f79c4025a1.jpeg)

**Comment by devanl** [comment]
Two updates, I’m still getting this error after disabling the app toggles for all location update sources. Also, the screenshot below appears to be events in the log on app from the time the notification occurs. 

![FF067B3F-7D6C-4AC4-B77A-BB33523BA84B](https://user-images.githubusercontent.com/4000925/58923941-c6bc5000-870f-11e9-8c26-33d50bebccec.jpeg)

**Comment by AZDane** [comment]
I get this when I leave my house. I’m in a cell dead zone, so it makes sense. 
I would be nice if the app could just wait with sending an update until it gets sufficient service. I’m guessing it tests for connection before sending, but then looses it in the middle of sending. 
Instead of throwing an error, just try again when connection is reestablished.

**Comment by ArgoHA** [comment]
Same thing here. Get the message when I leave house on car.

**Comment by brahmafear** [comment]
Bump on this issue.  Been happening ever since I installed 2.0 beta.  I'm fine with clearing the error (it is a beta afterall), but these errors seem to be triggering my failed login IP ban and hence my HomeAssistant instance keeps banning me.

**Comment by robbiet480** [comment]
These are appearing because there is actually a problem happening when we are trying to send a location & sensors update back to HA. Previously to this error existing though, it would just silently fail without you knowing. The only change that happened here was me adding a notification with the actual error. A notification appearing on your iPhone would not trigger a failed login IP ban...

I assume you aren't all getting the exact same message, `kCLErrorDomain code 2`, right? I can silence that one specifically, since it just means Apple's geocode server is rejecting too many requests from your device, but all other errors should be treated as valid.

**Comment by devanl** [comment]
A related issue, trying to silence these on my own I disable all the update sources in the app for location and the error still shows up regularly.

**Comment by brg468** [comment]
I think this is related to this topic.. I get this message fairly constantly when I’m on the move. The location does seem to be updated correctly in HA even with this message, it’s just a nuisance. Latest build, using HA Cloud. 

![57D74D93-C44D-4FC3-B991-F1306C718544](https://user-images.githubusercontent.com/19143191/59695836-e4ca8b80-91b8-11e9-99b2-4e38750c5f50.png)

**Comment by brahmafear** [comment]
I understand the failure messages aren't causing my IP ban to trigger, but
I'm wondering if those 500 messages are related.  The *only* IPs that are
getting banned are my mobile phone's IP while on mobile network and the IP
of a remote location where I connect to wifi.

I've reset config for the beta mobile app for now (in order to disconnect
it from my HA instance) to see if the IP bans cease.  If so, that would
suggest the beta app is causing the IP bans.

If it makes a difference:
Using latest beta build (according to TestFlight).
Using latest HA build on HassIO (running in docker on Ubuntu 18.04).
Using direct IP connection to my home ISP/endpoint.  Ie, not Casa/Cloud.

Never had these issues on 1.0 or 1.5 series of iOS app.  Just 2.0 builds.

**Comment by brahmafear** [comment]
One more detail to provide:  These are the messages showing up in HA logs.
The IP corresponds with my mobile's IP address on either cell network or
remote wifi.

Login attempt or request with invalid authentication from X.X.X.X

**Comment by brg468** [comment]
This is what I get on the server side every time I refresh the app or get one of the '500' messages that I posted above.  Any thoughts?

```
2019-06-19 12:44:20 ERROR (MainThread) [hass_nabucasa.iot] Error handling message
Traceback (most recent call last):
  File "c:\python\home-assistant\lib\site-packages\hass_nabucasa\iot.py", line 220, in _handle_connection
    self.cloud, msg["handler"], msg["payload"]
  File "c:\python\home-assistant\lib\site-packages\hass_nabucasa\iot.py", line 274, in async_handle_message
    return await handler(cloud, payload)
  File "c:\python\home-assistant\lib\site-packages\hass_nabucasa\iot.py", line 316, in async_handle_webhook
    return await cloud.client.async_webhook_message(payload)
  File "c:\python\home-assistant\lib\site-packages\homeassistant\components\cloud\client.py", line 185, in async_webhook_message
    response_dict = utils.aiohttp_serialize_response(response)
  File "c:\python\home-assistant\lib\site-packages\homeassistant\components\cloud\utils.py", line 11, in aiohttp_serialize_response
    'body': response.text,
  File "c:\python\home-assistant\lib\site-packages\aiohttp\web_response.py", line 597, in text
    return self._body.decode(self.charset or 'utf-8')
AttributeError: 'StringPayload' object has no attribute 'decode'
```

**Comment by brg468** [comment]
Well of course it had to be something as simple as upgrading to the latest HA version...So far the 500 errors have stopped.

**Comment by TomBrien** [comment]
I believe this is addressed in release. Although genuine errors are of course still possible. Closing but feel free to reopen if still an issue
