### ISSUE TITLE
Slow reaction to unplugging event

### ISSUE THREAD

**Issue by gobartos** [home-assistant/home-assistant-iOS#383]
I've based some HA-automations on unplugging my iphone in the morning. This event is updated very slowly apparently. I mostly get quick reaction when I press 'Update Push events' in the settings of the iOS app. Which is not very normal. Ideas?

**Comment by TomBrien** [comment]
All the sensor values are only updated when the location is sent I believe.

**Comment by gobartos** [comment]
OK thanks I'm going to try: activate location again (which is disabled now) and then see if the unplugging event appears earlier.

**Comment by gobartos** [comment]
You we’re totally right: with location on, it works. Weird that this is related. Is there another way (from battery management perspective). Thanks anyway!

**Comment by gobartos** [comment]
I might have been to enthusiast yesterday: the plug unplug event is registered very late even with location and motion sensor on in iOS.

**Comment by SeanPM5** [comment]
What you can do is just open the app and pull to refresh. That immediately updates all sensors including the battery state one. I use this method to trigger my bedtime and morning routine automations faster.

You could also set up a voice shortcut to do this (App Configuration -> Siri Shortcuts -> Send Location) so that you can trigger the update by voice (for example "Hey Siri, I'm Awake"). If your phone is unplugged it will trigger the automations by voice without having to open the app.

Ideally there would be a way to tap into system events when the phone was unplugged or plugged in so this stuff could be triggered immediately, but I don't believe that is possible for third party developers. Maybe Robbie could chime in on that.

**Comment by robbiet480** [comment]
There's no way currently for me to get alerted when the battery status changes. Maybe iOS 13 but I wouldn't expect it because Apple probably sees only very limited use for apps to know when battery state changes.
