### ISSUE TITLE
 location error in China, maybe also in other countries.

### ISSUE THREAD

**Issue by xcray** [home-assistant/home-assistant-iOS#411]
The HA zone with the value of latitude/longitude came from iphone is displayed correctly on the map (via the menu of map, OpenStreetMap), but  not correct in the "Devices & Zones" map with the error of about 570 meters (with the direction of about 8:30, i.e. 255 degree, system map, AutoNavi-Gaode-in China).

**Comment by robbiet480** [comment]
I'm assuming this has something to do with the [China GPS Shift Problem](https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#GPS_shift_problem) and not something I can easily fix (or would, since it could cause the app to be banned in China.

I would assume iOS would automatically transform coordinates but maybe not. Not really sure whats going on.

**Comment by xcray** [comment]
@robbiet480 Thanks for your comment!
Sure, it is the China GPS shift problem.
How about using OpenStreetMap in "Devices & Zones" also? as same as the menu item "map".
If we don't touch the system map (at least in China), then everything could be fine.
Am I right?

**Comment by robbiet480** [comment]
Are you saying that the official Apple Maps app (not the map view inside of Home Assistant) is correct but my app is wrong? Trying to understand still.

**Comment by xcray** [comment]
Haha, the official Apple Maps app is using the stupid "Mars Coordinate System" in China, as required by the administration. In fact, it use map data from a Chinese company named Autonavi (Chinese name Gaode) in China, not Google or Apple's data, of course, based on the "Mars Coordinate System".
Currently, in the Homeassistant app, the latitude/longitude values are based on WGS84 since it's obtained directly from GPS, then it can be displayed correctly on OpenStreet Map (even in China), but can't be displayed correctly on System Map in China. unfortunately, the "Devices & Zones" function of Homeassistant app is using the system map, while the menu of "Map" of ha app is using OpenStreet map.

**Comment by robbiet480** [comment]
Okay got it. [Here's some more info](https://www.sinosplice.com/life/archives/2013/07/16/a-more-complete-ios-solution-to-the-china-gps-offset-problem) and some sample code [here](https://github.com/nsdata/CorelocationCategory) and [here](https://github.com/leavez/NO-BUS.app/tree/master/libs/ChinaShift) and probably best of all [here](https://gist.github.com/larryhou/9e3fa0a5f6fb1b0a0be7#file-chinagps-swift).

So the problem is that iOS only shifts the coordinates if they are the users current location. Other times, it gives WGS coordinates back. So I guess I just need to implement a shift function if users locale or location is China.

**Comment by xcray** [comment]
Yes, that's the point. 
But I am not sure about the coord sys of the realtime coordinates from iOS (I guess it's WGS84).
From my understanding, the system map app (and other map/navi apps) knows that the map data is based on Mars coord sys (officially name GCJ02), then it will transform the values from WGS84 to GCJ02.
Anyhow, this issue could be closed now.
Again, Thanks for your excellent app.
