### ISSUE TITLE
GPS Accuracy filter

### ISSUE THREAD

**Issue by jjpeet** [home-assistant/home-assistant-iOS#43]
Hi,
I've setup a notification which tells me when one of the five people in my household (using the iOS app) enter and exit the 5 zones I've setup. Have been running it this way for 3 or 4 months (since it was released). Yes - I get a few notifications...

As part of the notification, I also include the GPS accuracy because it was miss reporting that someone had exited a zone when they hadn't. Turns out, when this happens, the GPS accuracy is often 1000.

So can the app have a setting which filters out (stops) location updates if the GPS accuracy is above a number (eg, I would type in 900 or something like that).

This will stop my garage mysteriously opening at 3am because someone's iPhone thinks it left the home zone and then re-entered (when the GPS accuracy comes back)!

I'd love to have a go at this myself, but I I wouldn't know where to start.

Thx
James

**Comment by jjpeet** [comment]
Hi @robbiet480 any thoughts on this one?
Thx
JP

**Comment by robbiet480** [comment]
Hey @jjpeet, sorry for delay in getting back to you on this.

What are you are saying makes sense. When I do a request for one off location (that is, a location event that I generated, not getting your location on zone enter/exit or via significant location updates) I set the accuracy to `neighborhood` The reason it's set to `neighborhood` is because it is (usually) a good trade off between accuracy and time it takes to get a location. If I requested `accuracy` `room` then it could take a lot longer to get a location update. Here's all the levels I can use:

- `any`: Lowest accuracy (< 1000km is accepted)
- `country`: Lower accuracy (< 100km is accepted)
- `city`: City accuracy (<= 3km is accepted)
- `neighborhood`: Neighborhood accuracy (less than a kilometer is accepted)
- `block`: Block accuracy (hundred meters are accepted)
- `house`: House accuracy (nearest ten meters are accepted)
- `room`: Best accuracy

While you are in your zone, some background location updates still happen, specifically background fetch (meaning iOS wakes up the app for a minute to let us do work) or significant location updates (which shouldn't be happening since you are staying in one place, not jumping cell towers, etc... assuming you aren't turning your phone off because you sleep for 48+ hours which would cause a update... anyway). These background location updates are what is causing you to jump in and out of a zone because of high accuracy levels even though you aren't moving.

I've been thinking recently about a location engine refactor now that i've learned a lot more since originally building it and have a lot more data from users. Here's a few fixes and improvements that I think should be implemented to fix your (and many others) issues.

1. If we are inside a pre-registered zone, don't update location during background fetch or significant location updates.
    - As of 1.1.1 you are kind of able to do this already by totally disabling background fetch or significant location updates in settings, but the problem with that is you will lose those updates when outside of zones.
    - We send battery data when updating your location as well, so disabling location updates while in zone would kill the battery tracking aspect. I could either split that call up into two or continue sending location updates but use the lat/long of your zone while inside the zone.
2. Allow changing the accuracy level for each trigger. This would allow you to set room level accuracy for manual updates and push notification requested updates and neighborhood for background fetch. 
3. Probably implement a history of updates sent to the server along with what triggered that update. I'm already logging this info in the app but am not storing it anywhere.
4. iBeacons, especially when you have a lot of them, also pose an issue since you could be walking around the house and falling out of zones at edges of iBeacon reception. Probably would need to implement some kind of timeout where if you don't re-enter zone within X minutes only then we would trigger an update stating you are out of zone.
5. Build a device tracker platform for iOS to "smooth out" location data

I don't know how I feel about a filter really. I'd probably only implement it if you selected the `city` or `country` level just so that I could add some extra steps in between that level and the next lowest one.

I'll most likely continue to update this issue but those are my initial thoughts. Location is going to be my focus for the next few days, I hope to have significant improvements completed by 1.2.0.

Again, apologies for the delay, hope this was somewhat enlightening.

**Comment by cmsimike** [comment]
re: 4 - you had mentioned once you wanted somewhat feature parity with owntracks. The way owntracks deals with point 4 is that it allows you to specify a family of ibeacons as the same uuid and a major and minor version of 0.

This would allow you setting up as many ibeacons that have the same uuid and treat it entirely as 'home' zone, so you'd never fall out of it.

hope this was helpful.

**Comment by robbiet480** [comment]
@cmsimike We already support that exact thing. Just because you have multiple iBeacons doesn't mean you have full coverage of your house though. Sure you can move them, but you may not even know they need to be moved in the first place :)

**Comment by jjpeet** [comment]
Hi Robbie,

Thanks for the update.

From an accuracy perspective, the only actual "problem" that poor accuracy causes me is that I'm sitting at home, and suddenly HA says I'm not at home (1000m accuracy) and a little while later it says I'm home again (high accuracy).  Not a biggie, except that then my garage door opens (sometimes in the middle of the night while I'm asleep...).  

I guess if I was simply able to filter out location updates that had poor accuracy that would alleviate the issue somewhat. But given the other issues you've mentioned above, happy to defer to you on the best way forward.

I've recently started using beacons, and have turned on ibeacon notifications in the app settings. So far it has only ever exited the zone due to me being away from the beacon. Never once has it used the beacon for arrival at a zone. Even though I'm in the zone, and the GPS hasn't picked it up yet.  Not sure if that's a bug, but if that worked, then the timeliness of entering a zone would be largely solved.

My house is on the edge of the mobile network - so when at home, my phone only connects to a single mobile cell tower.

Anyway - for your thoughts. 

Thx
James

**Comment by cmsimike** [comment]
@robbiet480 really? i had no idea!! 
thank you for the heads up!

**Comment by jjpeet** [comment]
Hi @robbiet480, I'm wondering where I can find info on how to invoke a push notification location update? I've dug through the doc on the homeassistant site but can't find anything. I'm thinking that I can use this to alleviate some of my location timeliness issues...
Thx
James

**Comment by robbiet480** [comment]
https://www.home-assistant.io/docs/ecosystem/ios/notifications/requesting_location_updates/
