### ISSUE TITLE
opening from other apps via URL don't work

### ISSUE THREAD

**Issue by thinkJD** [home-assistant/home-assistant-iOS#45]
First i added an event trigger BedTime in Home-Assistant, and tested it with the debug tools. The event trigger works fine. Then i tried to call Home-Assistant-iOS from Workflow with the following urls:

`homeassistant://fire_event/custom_event?entity_id=BedTime`
`homeassistant://fire_event/BedTime`

Previously i tried a service call, also with no luck: 
`homeassistant://call_service/light.turn_on?entity_id=light.decke_kuche`

The app opens but nothing happens.

**Comment by thinkJD** [comment]
Oh, this time a got an error from Home-Assistant, but only for the service call: 
`2017-08-10` 20:56:14 ERROR (MainThread) [homeassistant.core] Invalid service data for light.turn_on: extra keys not allowed @ data['sourceApplication']. Got 'is.workflow.my.app'

**Comment by robbiet480** [comment]
I just tested this with `homeassistant://fire_event/custom_event?entity_id=BedTime` and saw an entry in my HASS logs. 

I did find an issue in the app when attempting to use `homeassistant://fire_event/BedTime` where it would crash. I have fixed that and it should be released soon.

I also improved Home Assistant itself (at https://github.com/home-assistant/home-assistant/pull/10451) so that calling a service properly throws error codes and messages which will properly display in the UI.

Finally, I added alert boxes that display after calling from another app so that you know it worked or didn't.
