### ISSUE TITLE
Switch positions don't update on app restart

### ISSUE THREAD

**Issue by wixoff** [home-assistant/home-assistant-iOS#46]
When opening the app I'm often greeted with stale/incorrect switch positions on the interface.  A light might be "on" but the switch in the app shows "off" if I operated the switch elsewhere (e.g. a hardware switch or through the web interface or an automation).

Despite it being visually incorrect it is still operative: a light that's "on" but showing up as "off," if tapped in the iOS interface, will turn off then show correctly.

To work around this I need to either force-quit and restart the app or go into the app's settings and exit back to the interface.  Either will trigger an update.  Simply exiting the app, doing something else on the phone, and reentering it does not trigger an update.

**Comment by mnoorenberghe** [comment]
@cwixon Do you see the "Connection lost. Reconnecting…" toast when this happens? I'm wondering if the WebSocket connection is getting disconnected. It wouldn't be hard to evaluate JS like the following in the webview if that is the problem:
```js
hassConnection.then(r => {
  if (r.socket.readyState != WebSocket.prototype.OPEN) {
    // reconnect
  }
})
```

**Comment by cwixon** [comment]
No, when I exit the app, do something else, then come back in there usually **isn't** that message but the switch positions are wrong.  After I **do** get the "Reconnecting..." message (e.g. after force-quitting the app or going into settings and back) I can usually trust that the switch positions are correct.

I haven't seen this problem lately, so maybe it was a transient thing in an early version of iOS 11.  I'm going to keep it open for now but will close it if I don't see it again in a while, since nobody has come in here to confirm.

**Comment by wixoff** [comment]
Still haven't seen it recur, not in a long while.  I think we can close this.
