### ISSUE TITLE
Select All in Dev Tools / Templates does not work.

### ISSUE THREAD

**Issue by Petro31** [home-assistant/home-assistant-iOS#464]
Title.

Attempting to use select all does not work in the Developer Tools -> Templates tab.  It acts like it selects it by moving the cursor to the end of the 'all text' block, but does not highlight everything.

I would assume this is the case for all the yaml fields that were added in ~0.99.  Although I have not checked.

This is broken in both the beta and 1.5 using HA v0.101.

**Comment by SeanPM5** [comment]
It's not an iOS-specific issue, it has to do with 0.101 switching to CodeMirror for the code editor. 

That brought some nice improvements like syntax highlighting and line numbers, but unfortunately it's not mobile-friendly whatsoever. You can see there's [dozens of mobile-related bugs](https://github.com/codemirror/CodeMirror/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+mobile) on their repo. Apparently they plan on addressing these issues with a [complete rewrite](https://discuss.codemirror.net/t/announcing-work-has-started-on-codemirror-6/1817) of the library (which started over a year ago) but that's probably a very long ways off still. 

Since this is more of a general frontend issue, I think the best course of action would be to open a "Don't use CodeMirror on mobile devices" feature request on the [HA frontend repo](https://github.com/home-assistant/home-assistant-polymer/issues/new/choose) explaining that it's not mobile-friendly.
