### ISSUE TITLE
iOS App not working

### ISSUE THREAD

**Issue by mpolazzo** [home-assistant/home-assistant-iOS#483]
Hi,
my iPhone XS just updated the Home Assistant App from the Apple App Store.
When I open it, it redirectls to my Home Assistant instance at home, asking for username and password.
After inputing username and password an error occurs. I try to translate it from Italian:
"Error: the component mobile_app has not been loaded. Please add it to the configuration, restart Home Assistant and retry".
I don't really know what to do.
Thanks for helping.

**Comment by TomBrien** [comment]
Please follow the migration guide [here](https://companion.home-assistant.io/getting_started/migration) appoliges but the traslation of the docs is far from complete.

The short answer to your problem is add either [`default_config:`](https://www.home-assistant.io/integrations/default_config/) or `mobile_app:` to your `configuration.yaml` file.

**Comment by mpolazzo** [comment]
> Please follow the migration guide [here](https://companion.home-assistant.io/getting_started/migration) appoliges but the traslation of the docs is far from complete.
> 
> The short answer to your problem is add either [`default_config:`](https://www.home-assistant.io/integrations/default_config/) or `mobile_app:` to your `configuration.yaml` file.

it worked.
Many thanks!
