### ISSUE TITLE
Copy PUSH ID in 2.0 - Mac Airdrop fails

### ISSUE THREAD

**Issue by h4nc** [home-assistant/home-assistant-iOS#484]
First of all thanks for the great update. 

While moving from 1.5 to 2.0 I saw the the PUSH ID in the settings changed and I wanted to copy it and send it to my mac using airdrop. 

I noticed that this did not work, nothing appears in the download folder (and I think Airdropped things can also end up there).

BTW: After setting everything up it looks like the PUSH ID isn't needed any more in the configuration. If it's  not needed anymore it would be nice to add this information [here](https://companion.home-assistant.io/en/getting_started/migration )

Anyway could you clarify and if possible test where the airdropped PUSH ID could have landed or why it isn't sent correctly, because I don't like to have some unknown ghost files somewhere on my laptop. 
And lastly if Airdrop doesn't work for that maybe it's possible to disable it for the app.

**Comment by TomBrien** [comment]
I don't think push id was ever needed in the configuration. I certainly ran a device using the 1.5 app with no need to keep it in config

**Comment by olbjan** [comment]
There is no reason (ever) to copy the push ID to HA manually... however this issue has nothing to do with the app but rather with ios core functionality.

The ID is visible and can be copied for cases where Robbie wants to debug notification  issues.

**Comment by h4nc** [comment]
Well I don't know and don't remember the setup process, but I always follow documentations when I set up things. Maybe Push ID  was needed for actionable notifications?

**Comment by h4nc** [comment]
I can only tell that I had it like this for months and it worked. Don't know where I got that from. Looked like this and the example needed the key.

```
notify:
  - platform: ios
    name: ios
    target: !secret notify_key_iphone
```

**Comment by TomBrien** [comment]
You just beat me to it. Worked out that is what you were doing. That was has been deprecated for a while

**Comment by h4nc** [comment]
@TomBrien ok thanks. I obviously missed that. 

Just one more thing (sry for my OCD ;) 
If you have a mac, could you try airdropping the pushID to your mac. As I said it won't be delivered. 
Could habe to reasons (from my point of few): 
- it fails without showing an error
- it's delivered but I can't find or see it

**Comment by h4nc** [comment]
Could some one test this and maybe clarify the question I had in my last post?

**Comment by SeanPM5** [comment]
I just tested and AirDrop fails for me too. It plays the chime that it was successful but no file ends up on my Mac.

If I had to guess the reason why, it's probably attempting to create a `.textClipping` file but there are special characters in the Push ID such as colons that aren't supported in Mac filenames, so it fails. But this is purely a guess...  

Very much seems like more of an issue on Apple's side though.

**Comment by h4nc** [comment]
@SeanPM5 thanks for trying this out.

I also heard the chime, which is why I thought the file must be somewhere.
Thanks for sharing your guess, would you say the file ist saved somewhere?

As this is not an issue of the app I will close this.

**Comment by SeanPM5** [comment]
Did a few quick tests and the AirDrop chime actually seems to occur when it's _sending_ the file. So it's really more of a "starting transfer" chime rather than "success" chime like I had originally thought. You can test this by AirDropping a video file to your Mac, you'll hear the chime before it even finishes transferring the file.

So I don't think the chime means anything in this case, it is a bit misleading. It seems to be failing to create the file in the first place. To give an example, if you highlight this text below, and then drag the text to your desktop, you'll see that it smartly replaces the unsupported colon characters in the filename with hyphens.

```dIt2:g64V:FakePushID```

If you then try to rename this file to include colons, you will get an error prompt "Try using a name with fewer characters, or with no punctuation marks."  My guess is that AirDrop is not intelligently renaming the file like it should, nor is it showing the error prompt. It's just failing in the background without the file ever being created, and the chime made this a little confusing.

This is entirely a guess on my part, but it seems like a plausible theory. And If I'm right it's a bug in AirDrop/macOS.

**Comment by h4nc** [comment]
You are right. Looks lie the chime only tells that something comes in.

I tried airdropping a the example above, but I doesn't create a file. 

After that I wrote `test` in notes, marked it and airdropped that. This airdrops a .txt file with the content "test" in it to my Download folder. But `test:test` fails. 

If you think you found a bug on the apple site, it would be great to report it somehow.

**Comment by robbiet480** [comment]
https://feedbackassistant.apple.com

feedbackassistant:// on iOS
