### ISSUE TITLE
Multiple ios devices cannot each use new notify service

### ISSUE THREAD

**Issue by ishults** [home-assistant/home-assistant-iOS#486]
When I upgrade to the new iOS Companion App, the integration I see created is "Mobile App: iPhone." I see a new service called "notify.mobile_app_iphone" and a new device_tracker (NOT called "mobile_app_<device_id>"). This was unexpected but worked fine for one phone. 

However, when another phone is added via the integration, it also says "Mobile App: iPhone" for its integration, and NO new notify service is created. This means that only one iPhone can get notifications with that service (whichever was registered first). I believe it's because both integrations are called "iPhone."

This doesn't seem to be the intended behavior, but I can't seem to rename anything properly to force a new notify service to be created. I've gone through onboarding multiple times and still can't figure out what's missing. Is this a bug, or is there a problem with my configuration?

I am running server version 0.102.2 and my config includes:
```
mobile_app:
ios:
discovery:
```
The services list:
![image](https://user-images.githubusercontent.com/7275442/69741076-0df42e00-1100-11ea-831c-be335dede9b7.png)

Integrations:
![image](https://user-images.githubusercontent.com/7275442/69741161-2d8b5680-1100-11ea-9658-7d306ce36178.png)

**Comment by SeanPM5** [comment]
This uses your iOS device name under iOS settings > General > About > Name. Both of your iOS devices appear to have identical names of of "iPhone" set there. 

This causes a conflict preventing the `notify` service from being registered on the second phone. It's trying to create/register `notify.mobile_app_iphone` again, but that name already exists so it fails. Hope this makes sense?

What you should do is to rename the second phone under iOS settings > General > About > Name so that it has a unique name. Then delete the app on your second phone and run the onboarding process again, this time it should create the notify service.

**Comment by ishults** [comment]
@SeanPM5 Yes, that did it! Thank you!

Should the onboarding process take into account duplicate phone names? I guess I'm not sure how common/uncommon the practice is to rename the phone, so perhaps it's not worth it.

**Comment by SeanPM5** [comment]
Glad you got it working and happy to help.

Yeah, I think that this could probably be improved upon. Ideally it should create the notify service but just add a `_2` or something on the second/duplicate phone. Or at least display some kind of clear error so the user knows precisely what's going on and how to fix.

This is a pretty rare issue, though. By default the phone is named with the users name and device model (for example "John's iPhone 6S") so it's uncommon to have duplicate names like this. And usually when people rename them, it's to make the names unique rather than identical, hehe. 

But you're not the first one to experience this issue so it's definitely something that should be looked into at some point. Thanks for reporting it :)
