### ISSUE TITLE
Notification History/List

### ISSUE THREAD

**Issue by cgarwood** [home-assistant/home-assistant-iOS#49]
It would be nice to have a notification history or list accessible in the app. I've occasionally unlocked my phone with HA notifications and had to do some digging to find them. If there was a button that listed the last 20 or so (with an option to clear/dismiss) that would be awesome.

**Comment by mnoorenberghe** [comment]
On my iPhone 6 with iOS 10.3.3, notifications don't automatically go away when the app opens so they should still be in your notification center unless you explicitly clear them. What am I missing?

If that doesn't address the issue, can you use the logbook for this?

**Comment by JCrankWV** [comment]
I would also like to see this feature added to the app.

Great work BTW on developing this app.

**Comment by gsportelli** [comment]
Even though this issue was closed in 2019, the current iOS companion app still *does not provide a usable notification history* that survives a normal tap on a notification.

Right now on iOS:

- Tapping a Home Assistant notification **opens the app but immediately clears the notification**, and the content/actions are lost.
- Action buttons only appear if you **long-press/expand the notification UI** in the system shade.
- There is no in-app list, inbox, or “last notification details” screen that shows the text + actions the app received once iOS has dismissed the banner.

This is particularly frustrating when notifications include actionable buttons (e.g., arming/disarming, garage controls). Many users (including in community discussions) expect an in-app history or at least a way to show the tapped notification content once the app is open. 

Feature requests that could meaningfully address this:

1. A **notification inbox/history UI** inside the iOS app showing recent notifications received by that device.
2. Alternatively, when the app is opened via a notification tap, show a **“notification details” view** that includes the full message and any action buttons that were present.

Currently, the only workaround is:
- long-pressing the notification to use its actions, or
- sending/persisting the notification content elsewhere (e.g., persistent notification, custom logbook entity).

This behavior remains a gap compared to Android’s notification history support and the expectation that notifications with actions remain actionable even after opening the app.

Thanks!
