### ISSUE TITLE
Siri commands long error

### ISSUE THREAD

**Issue by bobvmierlo** [home-assistant/home-assistant-iOS#497]
When trying to create a Siri Command to activate a scene I get the following error ([screenshot](https://imgur.com/a/HWnG2pu)) on my iPhone.
This Siri integration was working fine when running the app in Beta through Testflight. Now i've downloaded the official app from the appstore I can find the app within Siri Commands and I'm able to create a new command but everything I try results in the above shown error.

**Comment by SeanPM5** [comment]
The "Service Data" part requires JSON, you can't just type the entity_id as text or it will give you that error. I realize that this is not entirely clear since it asks for text.. It needs to be in this format, you can copy and paste this and try: 

`{"entity_id":"scene.dim_lights"}`

Screenshot below.

![json](https://i.imgur.com/LXosOUB.jpg)

**Alternate Method**
By placing a "Dictionary" action above the call service command, you can avoid having to type the JSON syntax and could just type the entity_id. Here is an example of using a dictionary.

![dictionary](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/optimized/3X/b/3/b3ca3482c8802de50df2332a44c58a2e6ef74e19_2_940x1000.jpeg)

Documentation for this will be coming soon.

**Comment by bobvmierlo** [comment]
Thanks for the clarification Sean! Works like a charm now.
Would be great if this would be in the documentation on [companion.home-assistant.io](https://companion.home-assistant.io/)
