### ISSUE TITLE
Use app-header-background-color as the default variable to set statusBar color.

### ISSUE THREAD

**Issue by Knapoc** [home-assistant/home-assistant-iOS#531]
Recently a new variable, `app-header-background-color`, got introduced to set the header color. Since the companion app uses `primary-color` and falls back to the default theme to set the statusBar color, some themes look off.

I think the logic should be following this order:
1. use app-header-background-color if defined
2. use primary-color if defined
3. assume that the default theme is used

![Image of app-header-background-color](https://i.imgur.com/MFCdArY.jpg)

**Comment by Phontana** [comment]
I'd like this one as well, since primary color isn't always the color you want for the status bar. Is it also possible to specify the color of the status bar icons (light/dark) by using a variable? This would make the modification of the status bar even more powerful, because right now the status bar text is always light and that makes it invisible on light status bar backgrounds.

**Comment by dwainscheeren** [comment]
And what @Phontana says a option to set the statusbar to dark mode?

**Comment by Phontana** [comment]
@dwainscheeren I will create another issue for that, and maybe a PR as well.
