### ISSUE TITLE
Cant download beta 2 with TestFlight 

### ISSUE THREAD

**Issue by jdenver13** [home-assistant/home-assistant-iOS#551]
Im getting 'This beta isn't accepting any new tester right now.' on my iPhone, am I doing something wrong?

**Comment by R5n3h** [comment]
Hi, I’m not sure if it’s related to this issue, but as from today, the current version of the beta is crashing on startup and not listed in the TestFlight app.

**Comment by TomBrien** [comment]
The beta build has expired. You should use the app released in the App Store which is the same as the last build on TestFlight

**Comment by nibblerrick** [comment]
Is it really the same? My Beta-app showed version 105.5, the appstore shows 102.3.
(That shouldn't say that you should not use the appstore-version.)

**Comment by TomBrien** [comment]
That’s the home assistant core version number you’re running. Build number is shown is shown in the about page.

**Comment by nibblerrick** [comment]
Damn, you are absolutely right.
I just have no idea why the not-beta showed 102.3 yesterday as they were connected to the same ha-instance. Whatever, today it also shows 105.5.
Because of the different versions yesterday I haven't looked thorough enough for the versioninformation of the app. Sorry for that and thanks for pointing in the right direction!

**Comment by robbiet480** [comment]
Yep, please use the App Store version for now.
