### ISSUE TITLE
Unable to scroll in logbook

### ISSUE THREAD

**Issue by JonasKristiansen** [home-assistant/home-assistant-iOS#560]
When opening logbook on iOS devices the logbook is useless. 

Only the intial list of entries is shown. When you try to scroll down the app instantly scrolls to the top again. This means you can always only see the last (approx.) 10 entries as you simply can´t scroll. 

Error can be seen here:
https://share.icloud.com/photos/0ykHq9hXo_ZF2d275IwpEAVtw

**Comment by TomBrien** [comment]
Do you see the same behaviour in Safari (or any other browser in iOS)?

**Comment by JonasKristiansen** [comment]
Hi, 

Yes. I see same behavior in Safari on my iPhone 11 Pro + my girlfriends iPhone 10. 

https://share.icloud.com/photos/0y-4eAS7nta6MGc5BIX6Dtq1A

Venlig hilsen
Jonas Kristiansen

**Comment by SeanPM5** [comment]
This was a frontend issue that is fixed in the upcoming version 0.107 which releases about two weeks from now. See here: https://github.com/home-assistant/frontend/pull/4950. 

Closing this now, but if it's still not fixed after 0.107 please open a new issue on the[ frontend repository](https://github.com/home-assistant/frontend/issues). Thanks.
