### ISSUE TITLE
Scheduled updates

### ISSUE THREAD

**Issue by neographikal** [home-assistant/home-assistant-iOS#80]
Using the latest versions of both the app and HA (0.60) I notice that the app won't update the phone data (location, charge status, battery %) in HA for hours. I can remedy this by forcing updates through the notification function, but this is limited to 150 calls per day.

I'd like the phone to give an update every X seconds independent of location changes, etc. It would be nice to have this option in the app so it sends out the update every X seconds.

**Comment by cmsimike** [comment]
iOS apps do not have the ability to schedule something like that due to Apple limitations. The best we can do is subscribe to specific events like on gps update or on significant change update (which is what the app does now, I believe).

**Comment by neographikal** [comment]
Hmm that's a shame; and there is no way around that 150 call/day limitation? It's the only way to force app to work reasonably well. On it's own it lags :)

**Comment by cmsimike** [comment]
My install of iOS hass has been fantastic in reporting. It has been better than owntracks for me, and owntracks only got nearly as good as hass ios with the introduction of ibeacons (not using ibeacons with hass ios))

as for the 150/day, that is a limit because the repo owner is currently paying for these alerts. you might be able to fork this repo and use your own personal keys (for firebase i think) and do a rebuild. a nice update to this project might allow the custom input of  keys or otherwise allow you to specify the account to use for notifications.

**Comment by robbiet480** [comment]
Closing a stale issue, especially since 1.5.0 improved timeliness of reporting so much.
