### ISSUE TITLE
HealthKit Integration

### ISSUE THREAD

**Issue by bjornorri** [home-assistant/home-assistant-iOS#85]
I think it would be pretty nice to expose data fields from HealthKit to Home Assistant as sensors via the app. I'd be willing to put some time into it myself, if this indeed a wanted feature.

**Comment by cmsimike** [comment]
@bjornorri this isn't the first time i've heard about a desire to expose healthkit as sensors to hass. I think a lot of people would enjoy that.

**Comment by Nyqi** [comment]
Yes! It would be great to use it with smart scales for ex.

**Comment by robbiet480** [comment]
HealthKit integration is tough because we can only access the data when the phone is unlocked, so updates being pushed to sensors would be few and far between...

**Comment by robbiet480** [comment]
Not exactly HealthKit, but... Pedometer data is now in 2.0 via 47fed9286a61e7de226aa2afaddaae042fee1177. The data includes:

- `startDate` - The start time for the pedometer data.
- `endDate` - The end time for the pedometer data.
- `numberOfSteps` - The number of steps taken by the user.
- `distance` - The estimated distance (in meters) traveled by the user.
- `averageActivePace` - The average pace of the user, measured in seconds per meter.
- `currentPace` - The current pace of the user, measured in seconds per meter.
- `currentCadence` - The rate at which steps are taken, measured in steps per second.

**Comment by robbiet480** [comment]
Also, revisiting the specific request for HealthKit, since this was first requested Apple has [published some documentation around getting approval for Health](https://developer.apple.com/documentation/healthkit/protecting_user_privacy) stating: `In addition, your app must not access the HealthKit APIs unless the app is primarily designed to provide health or fitness services. Your app's role as a health and fitness service must be clear in both your marketing text and your user interface.` so it's unlikely that the app would get approved anyway since it's primarily NOT designed to provide health or fitness services.

So i'm going to close this issue. Sorry y'all!

**Comment by westenberg** [comment]
For people who are looking for a solution to get Home Assistant sensor data to the iOS Health app: you can use Shortcuts on iOS with the render template task to get a value out of Home Assistant and use an Health app task to get the data in the iOS Health app. Only disadvantage is that you have to manually approve the execution on your phone or have to manually execute the shortcut.

Personally I would prefer to have all my data in Home Assistant but it won't work because iOS Health is too much integrated with the Apple Watch and I can't track my activities in Home Assistant (except for now reading some basic sensors like steps, stairs).

So: what if we would make a dedicated Home Assistant health app (also for watch) to track this data and store the data in Home Assistant and optionally sync it with the Health app.

**Comment by fivestones** [comment]
> Only disadvantage is that you have to manually approve the execution on your phone or have to manually execute the shortcut.

You no longer have to manually approve the execution or manually execute the shortcut. You can now make shortcuts with the Shortcuts app that will run in the background at certain times or under certain conditions occur (e.g., you arrived at home, you opened a certain app) which will run without any manual approval. They do make a pop-up notification occur on the phone showing that they occurred, but they will occur without any personal interaction.

**Comment by fivestones** [comment]
> what if we would make a dedicated Home Assistant health app (also for watch)

I'm all for this. I would really love to get at this data easily.

> so it's unlikely that the app would get approved anyway since it's primarily NOT designed to provide health or fitness services.

There are many, many apps in the app store that access Apple Health data which are not primarily health or fitness apps--they are instead apps that are used to monitor info from your phone, a few of them being specifically to get that data off the phone and onto a server or computer elsewhere (including information such as phone location, gyroscope information, elevation, battery life, etc., so not primarily health apps, and not advertised primarily as health apps. Even precursor to the 
Apple Shortcuts app, which was not made by apple, accessed Apple HealthKit data and was certainly not a health or fitness app.

> 

Also, there are many, many apps in the app store that are not

**Comment by tensiondriven** [comment]
Second this, if the iOS HomeAssistant app could retrieve health data and display it in the app, I think there's a case to be made that this would qualify for the entitlements to retrieve health data.

**Comment by fivestones** [comment]
@robbiet480 Can we reopen this issue? I think it's clear now that the problem that lead you to close this is no longer an problem.

**Comment by zacwest** [comment]
I'll convert this to a feature request discussion, but keep in mind: the only way to know whether Apple would permit it is to _build it_ and pray. That's sometimes worthwhile (it's the approach I did with the focus sensor, which we are using out of the norms) but it's also sometimes just a mentally draining exercise.
